---
- name: Clone bash-it
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: repos/bash-it
    version: "v{{ bash_it_version }}"

- name: Clone gitstatus
  git:
    repo: https://github.com/romkatv/gitstatus.git
    dest: repos/gitstatus
    depth: 1

