---
- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf
    dest: repos/fzf
    version: "{{ fzf_version }}"

- name: Build fzf
  command:
    cmd: "./install --no-update-rc"
    chdir: "repos/fzf"
    creates: "repos/fzf/bin/fzf"

- name: Clone fzf-git
  git:
    repo: https://github.com/junegunn/fzf-git.sh
    dest: repos/fzf-git.sh
