---
- name: Setup bat
  hosts: all
  tags: bat
  vars:
    bat_binary: "{{ '/usr/bin/batcat' if dev_setup_platform == 'ubuntu' else homebrew_prefix + '/bin/bat' }}"
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Install bat on Ubuntu
      become: true
      ansible.builtin.apt:
        name: bat
        state: present
      when: dev_setup_platform == 'ubuntu'

    - name: Install bat on macOS
      community.general.homebrew:
        name: bat
        state: present
        update_homebrew: "{{ homebrew_update | bool }}"
        path: "{{ homebrew_prefix }}/bin"
      when: dev_setup_platform == 'macos'

    - name: Create local bin directory
      ansible.builtin.file:
        dest: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: "0755"

    - name: Symlink bat
      ansible.builtin.file:
        src: "{{ bat_binary }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
        state: link
      with_items:
        - bat
        - cat
