---
- name: Setup bat
  hosts: all
  tags: bat
  tasks:
    - name: Install bat
      become: true
      apt:
        name: bat
        state: present

    - name: Create local bin directory
      file:
        dest: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: "0755"

    - name: Symlink bat
      file:
        src: /usr/bin/batcat
        dest: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
        state: link
      with_items:
        - bat
        - cat
