---
- name: Setup bazel
  hosts: all
  tags: bazel
  vars:
    bazelisk_asset: "{{ 'bazelisk-linux-amd64' if dev_setup_platform == 'ubuntu' else 'bazelisk-darwin-arm64' }}"
    bazelisk_checksum: "{{ bazelisk_linux_checksum if dev_setup_platform == 'ubuntu' else bazelisk_macos_checksum }}"
    bazel_buildtools_target: "{{ 'linux-amd64' if dev_setup_platform == 'ubuntu' else 'darwin-arm64' }}"
    bazel_buildifier_checksum: "{{ bazel_buildifier_linux_checksum if dev_setup_platform == 'ubuntu' else bazel_buildifier_macos_checksum }}"
    bazel_buildozer_checksum: "{{ bazel_buildozer_linux_checksum if dev_setup_platform == 'ubuntu' else bazel_buildozer_macos_checksum }}"
    bazel_unused_deps_checksum: "{{ bazel_unused_deps_linux_checksum if dev_setup_platform == 'ubuntu' else bazel_unused_deps_macos_checksum }}"
  tasks:
    - name: Create local bin directory
      file:
        dest: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: "0755"

    - name: Fetch bazelisk
      get_url:
        url: "https://github.com/bazelbuild/bazelisk/releases/download/v{{ bazelisk_version }}/{{ bazelisk_asset }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/{{ bazelisk_asset }}"
        checksum: "sha256:{{ bazelisk_checksum }}"
        mode: "0755"

    - name: Link bazelisk
      file:
        src: "{{ ansible_env.HOME }}/.local/bin/{{ bazelisk_asset }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/bazel"
        state: link

    - name: Fetch buildifier
      get_url:
        url: "https://github.com/bazelbuild/buildtools/releases/download/v{{ bazel_buildtools_version }}/buildifier-{{ bazel_buildtools_target }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/buildifier-{{ bazel_buildtools_target }}"
        checksum: "sha256:{{ bazel_buildifier_checksum }}"
        mode: "0755"

    - name: Link buildifier
      file:
        src: "{{ ansible_env.HOME }}/.local/bin/buildifier-{{ bazel_buildtools_target }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/buildifier"
        state: link

    - name: Fetch buildozer
      get_url:
        url: "https://github.com/bazelbuild/buildtools/releases/download/v{{ bazel_buildtools_version }}/buildozer-{{ bazel_buildtools_target }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/buildozer-{{ bazel_buildtools_target }}"
        checksum: "sha256:{{ bazel_buildozer_checksum }}"
        mode: "0755"

    - name: Link buildozer
      file:
        src: "{{ ansible_env.HOME }}/.local/bin/buildozer-{{ bazel_buildtools_target }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/buildozer"
        state: link

    - name: Fetch unused_deps
      get_url:
        url: "https://github.com/bazelbuild/buildtools/releases/download/v{{ bazel_buildtools_version }}/unused_deps-{{ bazel_buildtools_target }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/unused_deps-{{ bazel_buildtools_target }}"
        checksum: "sha256:{{ bazel_unused_deps_checksum }}"
        mode: "0755"

    - name: Link unused_deps
      file:
        src: "{{ ansible_env.HOME }}/.local/bin/unused_deps-{{ bazel_buildtools_target }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/unused_deps"
        state: link

    - name: Fetch repo tool
      get_url:
        url: "{{ repo_tool_url }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/repo"
        checksum: "sha256:{{ repo_tool_checksum }}"
        mode: "0755"

    - name: Enable bazel bashrc snippet
      file:
        src: "{{ inventory_dir }}/bashrc.d/{{ item }}"
        dest: "{{ inventory_dir }}/bashrc.d/enabled/{{ item }}"
        state: link
      with_items:
        - "003-bazel-helpers.bashrc"
