---
- name: Common pre-requisites
  hosts: all
  tasks:
    - name: Install python3-psutil (needed by dconf module)
      become: true
      apt:
        name: python3-psutil
        update_cache: yes
        state: present

    - name: Create tarballs directory
      file:
        path: "{{ inventory_dir }}/tarballs"
        state: directory
