---
- name: Some extra stuff that is nice to have around
  hosts: all
  tags: extras
  vars:
    chrome_deb: "google-chrome-stable_current_amd64.deb"
    horizon_url: "https://download3.omnissa.com/software/CART25FQ2_LIN64_DEBPKG_2406"
    horizon_deb: "VMware-Horizon-Client-2406-8.13.0-9995429239.x64.deb"
  tasks:
    - name: Install other apt packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - bmon
        - curl
        - git
        - graphviz
        - jq
        - python3-pip
        - python3-venv
        - virt-manager

    - name: Install apt packages not installable in Github Actions
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
      when: ansible_env.IS_GITHUB_CI is not defined

    - name: Install git-toprepo
      pip:
        name: git-toprepo
        extra_args: --user

    - name: Download google-chrome-stable
      get_url:
        url: "https://dl.google.com/linux/direct/{{ chrome_deb }}"
        dest: "{{ inventory_dir }}/tarballs/{{ chrome_deb }}"

    - name: Install google-chrome-stable
      become: true
      apt:
        deb: "{{ inventory_dir }}/tarballs/{{ chrome_deb }}"
        state: present

    - name: Download vmware-horizon-client
      get_url:
        url: "{{ horizon_url }}/{{ horizon_deb }}"
        dest: "{{ inventory_dir }}/tarballs/{{ horizon_deb }}"

    - name: Install vmware-horizon-client
      become: true
      apt:
        deb: "{{ inventory_dir }}/tarballs/{{ horizon_deb }}"
        state: present
