---
- name: Setup fzf
  hosts: all
  tags: fzf
  tasks:
    - name: Clone fzf
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf
        dest: "{{ inventory_dir }}/repos/fzf"
        version: "v{{ fzf_version }}"
      register: fzf_clone

    - name: Build fzf
      ansible.builtin.command:
        cmd: "./install --no-update-rc"
        chdir: "{{ inventory_dir }}/repos/fzf"
      when: fzf_clone.changed # noqa: no-handler
      changed_when: true

    - name: Clone fzf-git
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf-git.sh
        dest: "{{ inventory_dir }}/repos/fzf-git.sh"
        version: "{{ fzf_git_commit }}"

    - name: Enable fzf bashrc snippet
      ansible.builtin.file:
        src: "{{ inventory_dir }}/bashrc.d/{{ item }}"
        dest: "{{ inventory_dir }}/bashrc.d/enabled/{{ item }}"
        state: link
      with_items:
        - "005-fzf.bashrc"
