---
- name: Setup fzf
  hosts: all
  tasks:
    - name: Clone fzf
      git:
        repo: https://github.com/junegunn/fzf
        dest: "{{ inventory_dir }}/repos/fzf"
        version: "{{ fzf_version }}"

    - name: Build fzf
      command:
        cmd: "./install --no-update-rc"
        chdir: "{{ inventory_dir }}/repos/fzf"
        creates: "{{ inventory_dir }}/repos/fzf/bin/fzf"

    - name: Clone fzf-git
      git:
        repo: https://github.com/junegunn/fzf-git.sh
        dest: "{{ inventory_dir }}/repos/fzf-git.sh"
