---
- name: Setup glow
  hosts: all
  tags: glow
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ ansible_facts.env.PATH }}"
  tasks:
    - name: Install glow on macOS
      community.general.homebrew:
        name: glow
        state: present
        update_homebrew: "{{ homebrew_update | bool }}"
        path: "{{ homebrew_prefix }}/bin"
      when: dev_setup_platform == 'macos'

    - name: Fetch glow on Ubuntu
      ansible.builtin.get_url:
        url: "https://github.com/charmbracelet/glow/releases/download/v{{ glow_version }}/glow_{{ glow_version }}_{{ dev_setup_artifacts.glow_deb_arch }}.deb"
        dest: "{{ inventory_dir }}/tarballs/glow_{{ glow_version }}_{{ dev_setup_artifacts.glow_deb_arch }}.deb"
        checksum: "sha256:{{ glow_ubuntu_checksum }}"
        mode: "0644"
      when: dev_setup_platform == 'ubuntu'

    - name: Install glow on Ubuntu
      become: true
      ansible.builtin.apt:
        deb: "{{ inventory_dir }}/tarballs/glow_{{ glow_version }}_{{ dev_setup_artifacts.glow_deb_arch }}.deb"
        state: present
      when: dev_setup_platform == 'ubuntu'
