---
- name: Setup mdcat
  hosts: all
  tags: mdcat
  vars:
    mdcat_target: "{{ dev_setup_artifacts.mdcat_target }}"
    mdcat_archive: "mdcat-{{ mdcat_version }}-{{ mdcat_target }}"
  tasks:
    - name: Create local bin directory
      ansible.builtin.file:
        dest: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: "0755"
      when: dev_setup_platform == 'ubuntu'

    - name: Download mdcat
      ansible.builtin.get_url:
        url: "https://github.com/swsnr/mdcat/releases/download/mdcat-{{ mdcat_version }}/{{ mdcat_archive }}.tar.gz"
        dest: "{{ inventory_dir }}/tarballs/{{ mdcat_archive }}.tar"
        checksum: "sha256:{{ mdcat_linux_checksum }}"
        mode: "0644"
      when: dev_setup_platform == 'ubuntu'

    - name: Extract mdcat
      ansible.builtin.unarchive:
        src: "{{ inventory_dir }}/tarballs/{{ mdcat_archive }}.tar"
        dest: "{{ inventory_dir }}/tarballs"
        remote_src: true
        creates: "{{ inventory_dir }}/tarballs/{{ mdcat_archive }}/mdcat"
      when: dev_setup_platform == 'ubuntu'

    - name: Link mdcat
      ansible.builtin.file:
        src: "{{ inventory_dir }}/tarballs/{{ mdcat_archive }}/mdcat"
        dest: "{{ ansible_env.HOME }}/.local/bin/mdcat"
        state: link
      when: dev_setup_platform == 'ubuntu'

    - name: Create local man directory
      ansible.builtin.file:
        dest: "{{ ansible_env.HOME }}/.local/share/man/man1"
        state: directory
        mode: "0755"
      when: dev_setup_platform == 'ubuntu'

    - name: Copy manfile
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/tarballs/{{ mdcat_archive }}/mdcat.1/mdcat.1"
        dest: "{{ ansible_env.HOME }}/.local/share/man/man1/mdcat.1"
        mode: "0644"
      register: manfile_copy
      when: dev_setup_platform == 'ubuntu'

    - name: Update mandb
      become: true
      ansible.builtin.command: mandb
      changed_when: false
      when:
        - dev_setup_platform == 'ubuntu'
        - manfile_copy.changed
