---
- name: Setup ranger
  hosts: all
  tags: ranger
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ ansible_facts.env.PATH }}"
  tasks:
    - name: Install ranger on Ubuntu
      become: true
      ansible.builtin.apt:
        name: ranger
        state: present
      when: dev_setup_platform == 'ubuntu'

    - name: Install ranger on macOS
      community.general.homebrew:
        name: ranger
        state: present
        update_homebrew: "{{ homebrew_update | bool }}"
        path: "{{ homebrew_prefix }}/bin"
      when: dev_setup_platform == 'macos'

    - name: Create ranger config directory
      ansible.builtin.file:
        path: "{{ ansible_facts.env.HOME }}/.config/ranger"
        state: directory
        mode: "0755"

    - name: Link ranger config
      ansible.builtin.include_tasks: tasks/guarded-link.yml
      vars:
        guarded_link_src: "{{ inventory_dir }}/ranger.conf"
        guarded_link_dest: "{{ ansible_facts.env.HOME }}/.config/ranger/rc.conf"
